doctorapp/cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    url(r'^home/', views.home, name='home'),
    path('itemlist/', views.itemlist, name='itemlist'),
    path('shoppingcart/', views.shoppingcart, name='shoppingcart'),
    path('search/', views.searchpage, name='searchpage'),
    path('searchitem/', views.search, name='search'),
    path('checkout/', views.checkout, name='checkout'),
    url('productpage/(?P<Id>[0-9]+)', views.product_page, name='product_page'),
    url('add_to_cart/(?P<Item_id>[0-9]+)', views.add_to_cart, name='add_to_cart'),
    url('remove_from_cart/(?P<Item_id>[0-9]+)', views.remove_from_cart, name='remove_from_cart'),
    url('remove_single_item_from_cart/(?P<Item_id>[0-9]+)', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    url('add_single_item_into_cart/(?P<Item_id>[0-9]+)', views.add_single_item_into_cart, name='add_single_item_into_cart')

]

doctorapp/doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views as user_view
from django.contrib.auth import views as auth_views

# app_name = 'doctorapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='user/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    ##### user related path#########################
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
    path('home/', include('home.urls')),
    # path('', include('django.contrib.auth.urls'))

]

doctorapp/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns=[
    path('', views.landing, name='landing'),
]

doctorapp/user/urls.py
from django.urls import path, include 
from django.conf import settings 
from . import views
from user import views as user_view 
from django.contrib.auth import views as auth
from django.conf.urls.static import static 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [ 
        # path('', views.index, name ='index'),
        path('login/', user_view.Login, name ='login'),
        path('profile/', user_view.profilepage, name ='profile'),
	path('logout/', auth.LogoutView.as_view(template_name ='home/landingpage.html'), name ='logout'), 
	path('register/', user_view.register, name ='register'),
        path('user/sent/', user_view.activation_sent_view, name="activation_sent"),
        path('user/activate/<slug:uidb64>/<slug:token>/', user_view.activate, name='activate'),
        # url('^', include('django.contrib.auth.urls')),
        # path('accounts/', include('allauth.urls')),
        # path('password_reset/', auth_views.PasswordResetView.as_view(template_name ='user/password_reset_form.html'), name='password_reset'),
        # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
        # path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm')
]

doctorapp/home/models.py
from django.db import models

# Create your models here.

doctorapp/home/views.py
from django.shortcuts import render
from cart.models import Item, Cart

# Create your views here.
def landing(request):
    all_items = Item.objects.all()
    if not request.user.is_authenticated:
        print('No one inside the app')
        num_items_in_cart = 0
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'home_active':'active'}
        return render(request, 'home/landingpage.html', context)
    else:
        user = request.user
        num_items_in_cart = user.profile.cart_items.all().count()
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'home_active':'active'}
        return render(request, 'home/landingpage.html', context)

doctorapp/home/templates/home/footer.html
<!-- Footer -->
<footer>
    <div class="container-fluid padding">
        <div class="row text-center">
            <div class="col-md-6">
                <img src="https://cdn2.iconfinder.com/data/icons/medicine-84/1000/Medicine-color-15-512.png" alt="logo" height="70px">
                <hr class="light">
                <p>Phone Number</p>
                <p>E-mail address</p>
                <p>Office Address</p>
            </div>
            <div class="col-md-6">
                <hr class="light">
                <h5>Service Areas</h5>
                <hr class="light">
                <p>Address</p>
                <p>Address</p>
                <p>Address</p>
                <p>Address</p>
            </div>
        <div class="col-12">
            <hr class="light-100">
            <h5>&copy; websiteName.com</h5>
        </div>
        </div>
    </div>
    </footer>

doctorapp/home/templates/home/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Landing Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
  <!-- <link href="https://fonts.googleapis.com/css?family=Forte"> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href="{% static 'home/navbar1.css' %}"  rel="stylesheet">
</head>
<body>
  {% block content %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        {% endif %}

 <!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top" id="custom-nav">
    <div class="container-fluid ">
        <a class="navbar-brand waves-effect" href="{% url 'home:landing' %}"><img src="https://image.flaticon.com/icons/png/512/32/32140.png" alt="logo" height="70px"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item {{home_active}}">
                    <a class="nav-link" href="{% url 'home:landing' %}">Home</a>
                </li>
                <li class="nav-item {{order_active}}">
                    <a class="nav-link" href="{% url 'cart:searchpage' %}">Order Medicines</a>
                </li>
                <li class="nav-item {{doctor_active}}">
                    <a class="nav-link" href="#">Search Doctors</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                    {%comment%}
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <span class="p1 fa-stack fa-2x has-badge" data-count="{{ num_items_in_cart }}">
                      <!-- <i class="p2 fa fa-circle fa-stack-2x"></i>  -->
                    <i class="p3 fas fa-shopping-cart xfa-inverse"></i>
                    </span>
                    {% else %}
                    <span class="p1 fa-stack fa-2x has-badge" data-count="0">
                        <!-- <i class="p2 fa fa-circle fa-stack-2x"></i>  -->
                      <i class="p3 fas fa-shopping-cart xfa-inverse"></i>
                    {% endif %}
                    <a id="special0" class="nav-link" href="{% url 'cart:shoppingcart' %}">Cart</a>
                </li>
                </div>
                {% if request.user.is_authenticated %}
                
                <li class="nav-item">
                    <a id="special1" class="nav-link" href="{% url 'user:logout' %}">
                        <i class="fas fa-user icon"></i>
                        Logout
                    </a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a id="special2" class="nav-link" href="{% url 'user:register' %}">
                        <i class="fas fa-user icon"></i>
                        Login
                    </a>
                </li>
                {% endif %}{%endcomment%}

                {% if request.user.is_authenticated %}
                <!-- <div class="cart"> -->
                <li class="nav-item" id='c1'>
                <a href="{% url 'cart:shoppingcart' %}"><span class="p1 fa-stack fa-2x has-badge" data-count="{{ num_items_in_cart }}">
                    <!-- <i class="p2 fa fa-circle fa-stack-2x"></i>  -->
                  <!-- <i class="p3 fas fa-shopping-cart fa-sm xfa-inverse"></i> -->
                  <img src="https://cdn0.iconfinder.com/data/icons/webshop-essentials/100/shopping-cart-512.png" height='40px' width='40px'>
                  </span></a>
                  
                </li>
                <!-- </div> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">
                      <!-- <i class="fas fa-user fa-sm icon"></i> -->
                      <img src="https://icons-for-free.com/iconfiles/png/512/friend+human+man+member+person+profile+user+users+icon-1320168707291252637.png" height='40px' width='40px'>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-default"
                      aria-labelledby="navbarDropdownMenuLink-333" style="top:45px;right:-14px;">
                      <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
                      <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>                    </div>
                  </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}">
                        Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}">
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Navbar
<nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Dropdown
          </a>
          <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default"
            aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav> -->
  <!--/.Navbar -->

  {%endblock%}
</body>

</html>