doctorapp/cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    url(r'^home/', views.home, name='home'),
    path('itemlist/', views.itemlist, name='itemlist'),
    path('shoppingcart/', views.shoppingcart, name='shoppingcart'),
    path('search/', views.searchpage, name='searchpage'),
    path('searchitem/', views.search, name='search'),
    path('checkout/', views.checkout, name='checkout'),
    url('productpage/(?P<Id>[0-9]+)', views.product_page, name='product_page'),
    url('add_to_cart/(?P<Item_id>[0-9]+)', views.add_to_cart, name='add_to_cart'),
    url('remove_from_cart/(?P<Item_id>[0-9]+)', views.remove_from_cart, name='remove_from_cart'),
    url('remove_single_item_from_cart/(?P<Item_id>[0-9]+)', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    url('add_single_item_into_cart/(?P<Item_id>[0-9]+)', views.add_single_item_into_cart, name='add_single_item_into_cart')

]

doctorapp/doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views as user_view
from django.contrib.auth import views as auth_views

# app_name = 'doctorapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='user/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    ##### user related path#########################
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
    path('home/', include('home.urls')),
    # path('', include('django.contrib.auth.urls'))

]

doctorapp/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns=[
    path('', views.landing, name='landing'),
]

doctorapp/user/urls.py
from django.urls import path, include 
from django.conf import settings 
from . import views
from user import views as user_view 
from django.contrib.auth import views as auth
from django.conf.urls.static import static 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [ 
        # path('', views.index, name ='index'),
        path('login/', user_view.Login, name ='login'),
        path('profile/', user_view.profilepage, name ='profile'),
	path('logout/', auth.LogoutView.as_view(template_name ='home/landingpage.html'), name ='logout'), 
	path('register/', user_view.register, name ='register'),
        path('user/sent/', user_view.activation_sent_view, name="activation_sent"),
        path('user/activate/<slug:uidb64>/<slug:token>/', user_view.activate, name='activate'),
        # url('^', include('django.contrib.auth.urls')),
        # path('accounts/', include('allauth.urls')),
        # path('password_reset/', auth_views.PasswordResetView.as_view(template_name ='user/password_reset_form.html'), name='password_reset'),
        # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
        # path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm')
]

doctorapp/user/models.py
from django.contrib.auth.models import User
from django.db import models
from cart.models import Cart
from django.db.models.signals import post_save
from django.dispatch import receiver

class History(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    ordered_date = models.DateTimeField()
    ordered_items = models.ManyToManyField(Cart)

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    cart_items=models.ManyToManyField(Cart)
    signup_confirmation = models.BooleanField(default=False)
    address = models.CharField(max_length=256, default=True)
    history = models.ManyToManyField(History)


@receiver(post_save,sender=User)
def update_profile_signal(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

doctorapp/user/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 

class UserRegisterForm(UserCreationForm): 
	email = forms.EmailField() 
	phone_no = forms.CharField(max_length = 20) 
	# first_name = forms.CharField(max_length = 20) 
	# last_name = forms.CharField(max_length = 20) 
	class Meta: 
		model = User 
		fields = ['username', 'email', 'phone_no', 'password1', 'password2'] 

doctorapp/user/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib import messages 
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.forms import AuthenticationForm 
from .forms import UserRegisterForm 
from django.core.mail import send_mail,EmailMultiAlternatives 
from django.template.loader import get_template 
from django.template import Context 
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.db import IntegrityError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMessage

def index(request):
	user = request.user
	num_items_in_cart=user.profile.cart_items.all().count()
	return render(request, 'home/navbar.html',{'num_items_in_cart':num_items_in_cart})


def activation_sent_view(request):
    return render(request, 'user/activation_sent.html')

def activate(request, uidb64, token):
	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
	except (TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	print(account_activation_token.check_token(user, token))
	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.profile.signup_confirmation = True
		user.save()
		login(request, user, backend='django.contrib.auth.backends.ModelBackend')
		return redirect('home:landing')
	else:
		return render(request, 'user/activation_invalid.html')


def register(request): 
	if request.method == 'POST':	
		form = UserRegisterForm(request.POST)
		print(form)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db()
			user.profile.email = form.cleaned_data.get('email')
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			subject = 'Please activate your Account'
			message = render_to_string('user/activation_request.html', {
				'user': user,
				'domain': current_site.domain,
				'uid': urlsafe_base64_encode(force_bytes(user.pk)),
				'token': account_activation_token.make_token(user),
			})
			print(message)
			email = EmailMessage('email_subject', message, to=[user.profile.email])
			email.send()
			messages.success(request, "Your account has been created ! You are now able to log in")
			return redirect('user:activation_sent')
	else: 
		form = UserRegisterForm()
	return render(request, 'user/login_page_1.html', {'form': form, 'title':'reqister here'}) 


def Login(request):
	if request.method=="POST":
		username=request.POST.get('username')
		password=request.POST.get('password1')
		print(username)
		print(password)
		user=authenticate(request, username=username, password=password)
		print(user)
		if user is not None:
			form=login(request, user)
			messages.success(request, f'Welcome {username} !!')
			user = request.user
			user.save()
			# print(user.profile.bio)
			return redirect('home:landing')
		else:
			messages.info(request, f'Account done, please login')
	form=AuthenticationForm()

	return render(request, 'home/landingpage.html', {'form':form, 'title':'log in','user':user})

def profilepage(request):
	user=request.user
	all_items = user.profile.cart_items.all()
	num_items_in_cart = all_items.count()
	# print(all_items)
	context = {'all_items':all_items, 'num_items_in_cart':num_items_in_cart}
	return render(request, 'user/profile.html', context)

doctorapp/user/templates/user/activation_invalid.html
<h3>Activation Invalid!!</h3>

doctorapp/user/templates/user/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

doctorapp/user/templates/user/activation_sent.html
<h3>Activation link sent! Please check your console or mail.</h3>

doctorapp/user/templates/user/logged_out.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

doctorapp/user/templates/user/login_page_1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
   <link href="{% static 'user/login_page_1.css' %}" rel="stylesheet">
   <!-- <link href="login_page_1.css" rel="stylesheet"> -->
</head>
<body>
   {% if form.errors %}
      <!-- Error messaging -->
      <div id="errors">
         <div class="inner">
            {{ form.non_field_errors }}
            <div class="alert alert-danger" role="alert">
               {% for field in form %}
                  {% if field.errors %}{{ field.label }}: {{ field.errors|striptags }}{% endif %}
               {% endfor %}
            </div>
            
         </div>
      </div>
      <!-- /Error messaging -->
   {% else %}
   
   {% endif %}
<div class="materialContainer">

   <div class="box">
      
      <div class="title">LOGIN</div>
      <form method="POST" action="{% url 'user:login' %}">
         {% csrf_token %}
      <div class="input">
         <!-- <label for="name">Username</label> -->
         <input type="text" name="username" id="id_username" placeholder="Username">
         <span class="spin"></span>
      </div>

      <div class="input">
         <!-- <label for="pass">Password</label> -->
         <input type="password" name="password1" id="id_password1" placeholder="Password">
         <span class="spin"></span>
      </div>

      <div class="button login">
         <button type="submit"><span>GO</span> <i class="fa fa-check"></i></button>
      </div>
      
      <a href="{% url 'password_reset' %}" class="pass-forgot">Forgot your password?</a>
      </form>
   </div>

   <div class="overbox">
      <div class="material-button alt-2"><span class="shape"></span></div>

      <div class="title">REGISTER</div>
      <form method="POST" action="{% url 'user:register' %}">
         {% csrf_token %}

      <div class="input">
         <!-- <label for="regname">Username</label> -->
         <input type="text" name="username" id="id_username" placeholder="Username">
         <span class="spin"></span>
      </div>

      <div class="input">
        <!-- <label for="regemail">Email</label> -->
        <input type="email" name="email" id="email" placeholder="Email">
        <span class="spin"></span>
     </div>

     <div class="input">
        <!-- <label for="regemail">Email</label> -->
        <input type="text" name="phone_no" id="id_phone_no" placeholder="Phone Number">
        <span class="spin"></span>
     </div>

      <div class="input">
         <!-- <label for="regpass">Password</label> -->
         <input type="password" name="password1" id="id_password1" placeholder="Password">
         <span class="spin"></span>
      </div>

      <div class="input">
         <!-- <label for="reregpass">Repeat Password</label> -->
         <input type="password" name="password2" id="id_password2" placeholder="Repeat Password">
         <span class="spin"></span>
      </div>

      <div class="button">
         <button type="submit"><span>NEXT</span></button>
      </div>
   </form>

   </div>

</div>
<script src="{% static 'user/login_page_1.js' %}"></script>
</body>
</html>

doctorapp/user/templates/user/password_reset.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html>
<head>
  <title>Payment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'user/password-reset.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'user/password_reset.css' %}"> -->



</head>
<body>
    <div class="block-heading">
        <h2>Reset Password</h2>
    </div>
    <div class="content-section shadow p-3 mb-5 bg-blue rounded">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-sm-12 col-md-12">
                <label for="email">Email</label>
                <input type="email" class="form-control m-0" placeholder="Email Address" id="email">
                </div>
                <div class="form-group col-sm-12 col-md-12">
                    <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
                </div>
            </div>
        </form>
    </div>
</body>

doctorapp/user/templates/user/password_reset_complete.html
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'home:landing' %}">Go to Homepage</a>
{% endblock content %}

doctorapp/user/templates/user/password_reset_confirm.html
{% load crispy_forms_tags %}
{% block content %}
{% load widget_tweaks %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
          {% endfor %}
        
          {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}
        
          {% for field in form.visible_fields %}
            <div class="form-group">
              {{ field.label_tag }}
        
              {% if form.is_bound %}
                {% if field.errors %}
                  {% render_field field class="form-control is-invalid" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control is-valid" %}
                {% endif %}
              {% else %}
                {% render_field field class="form-control" %}
              {% endif %}
        
              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

doctorapp/user/templates/user/password_reset_done.html
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>

doctorapp/user/templates/user/profile.html
{% include 'home/navbar.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'user/profile.css' %}">
<div class="block-heading">
    <h2>Profile</h2>
  </div>
<h4><b>Username:</b> {{user.username}}</h4>
<h4><b>Cart Items: </b></h4>
{% for oitem in all_items %}
<h4>{{oitem.item.name}}</h4>
{%endfor%}