doctorapp/cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    url(r'^home/', views.home, name='home'),
    path('itemlist/', views.itemlist, name='itemlist'),
    path('shoppingcart/', views.shoppingcart, name='shoppingcart'),
    path('search/', views.searchpage, name='searchpage'),
    path('searchitem/', views.search, name='search'),
    path('checkout/', views.checkout, name='checkout'),
    url('productpage/(?P<Id>[0-9]+)', views.product_page, name='product_page'),
    url('add_to_cart/(?P<Item_id>[0-9]+)', views.add_to_cart, name='add_to_cart'),
    url('remove_from_cart/(?P<Item_id>[0-9]+)', views.remove_from_cart, name='remove_from_cart'),
    url('remove_single_item_from_cart/(?P<Item_id>[0-9]+)', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    url('add_single_item_into_cart/(?P<Item_id>[0-9]+)', views.add_single_item_into_cart, name='add_single_item_into_cart')

]

doctorapp/doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views as user_view
from django.contrib.auth import views as auth_views

# app_name = 'doctorapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='user/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    ##### user related path#########################
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
    path('home/', include('home.urls')),
    # path('', include('django.contrib.auth.urls'))

]

doctorapp/payment/urls.py
from django.conf.urls import url
from . import views

app_name = 'payment'

urlpatterns=[
    url(r'^process/$', views.payment_process, name='process'),
    url(r'^done/$', views.payment_done, name='done'),
    url(r'^cancelled/$', views.payment_cancelled, name='cancelled'),



]

doctorapp/cart/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(blank=True,null=True)
    description = models.CharField(max_length=300)
    in_cart = models.BooleanField(default=False)
    image = models.CharField(blank=True, null=True, max_length=400)
    def __str__(self):
        return self.name

class Cart(models.Model):
    #current_user =  models.ForeignKey(User, on_delete=models.CASCADE)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    itemtotal=models.FloatField(blank=True,null=True)
    #
    # def __str__(self):
    #     return str(self.current_user.username)

    def get_total_item_price(self):
        return self.quantity*self.item.price

doctorapp/payment/models.py
from django.db import models

# Create your models here.

doctorapp/cart/views.py
from .models import Item, Cart
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.

def home(request):
    all_items = Item.objects.all()
    if not request.user.is_authenticated:
        print('No one inside the app')
        num_items_in_cart = 0
        return render(request, 'cart/index.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})
    else:
        user = request.user
        num_items_in_cart = user.profile.cart_items.all().count()
        return render(request, 'cart/index.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})

def itemlist(request):
    all_items = Item.objects.all()
    user = request.user
    if not user.is_authenticated:
        num_items_in_cart=0
        return render(request, 'cart/itemlist.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})
    num_items_in_cart=user.profile.cart_items.all().count()
    return render(request, 'cart/itemlist.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})

def shoppingcart(request):
    user = request.user
    print("Hey Dude")
    if not user.is_authenticated:
        num_items_in_cart=0
        return render(request, 'cart/shopping-cart.html', {'num_items_in_cart': num_items_in_cart})
    all_user_items = user.profile.cart_items.all()
    print(all_user_items)
    tot_cost = 0
    for i in all_user_items:
        print(i.quantity)
        tot_cost += i.itemtotal
    print(tot_cost)
    num_items_in_cart=user.profile.cart_items.all().count()
    return render(request, 'cart/shopping-cart.html', {'num_items_in_cart': num_items_in_cart, 'all_user_items': all_user_items, 'tot_cost': tot_cost})

def search(request):
    print(request.method)
    if request.method == 'POST':
        itemname = request.POST.get('itemname')
        print(itemname)
        item_obj = Item.objects.filter(name=itemname)
        num_items_in_cart = item_obj.count()
        if num_items_in_cart==0:
            messages.warning(request, "No such item!!")
            return redirect('cart:searchpage')
        context = {'all_items': item_obj , 'num_items_in_cart': num_items_in_cart}
        return render(request, 'cart/product_card.html', context)


def searchpage(request):
    all_items = Item.objects.all()
    user = request.user
    if not user.is_authenticated:
        num_items_in_cart=0
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'order_active': 'active'}
        return render(request, 'cart/product_card.html', context)
    paginator = Paginator(all_items, 4)
    page = request.GET.get('page')
    all_items = paginator.get_page(page)
    # paginate_by = 2
    num_items_in_cart = user.profile.cart_items.all().count()
    context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'order_active': 'active'}
    return render(request, 'cart/product_card.html', context)

def product_page(request, Id):
    item = get_object_or_404(Item, id=Id)
    user = request.user
    num_items_in_cart = user.profile.cart_items.all().count()
    return render(request, 'cart/product_page.html', {'num_items_in_cart':num_items_in_cart, 'item':item})

def add_to_cart(request, Item_id):
    item = get_object_or_404(Item, id=Item_id)
    check=0
    user = request.user
    if not user.is_authenticated:
        return redirect('user:register')
    for obj in user.profile.cart_items.all():
        if obj.item.id == item.id:
            obj.quantity=obj.quantity+1
            obj.itemtotal=(item.price)*float(obj.quantity)
            obj.save()
            check=1
    if check==0:
        temp=Cart()
        temp.item=item
        temp.quantity=1
        temp.itemtotal=(item.price)*float(temp.quantity)
        temp.save()
        user.save()
        user.profile.cart_items.add(temp)
        user.save()
        print(user.profile.cart_items.all())
    all_user_items = user.profile.cart_items.all()
    all_items = Item.objects.all()
    num_items_in_cart = user.profile.cart_items.all().count()
    tot_cost=0
    for i in all_user_items:
        print(i.quantity)
        tot_cost += i.itemtotal
    print(tot_cost)
    # return render(request, 'cart/product_card.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})
    return render(request, 'cart/shopping-cart.html', {'all_user_items': all_user_items ,'user':user,'num_items_in_cart':num_items_in_cart, 'tot_cost': tot_cost})

def add_single_item_into_cart(request, Item_id):
    item = get_object_or_404(Item, id=Item_id)
    user = request.user
    for obj in user.profile.cart_items.all():
        if obj.item.id == item.id:
            obj.quantity+=1
            obj.itemtotal=(item.price)*float(obj.quantity)
            obj.save()
    return redirect('cart:shoppingcart')

def remove_from_cart(request, Item_id):
    item = get_object_or_404(Item, id=Item_id)
    user = request.user
    for obj in user.profile.cart_items.all():
        if obj.item.id == item.id:
            user.profile.cart_items.filter(id=obj.id ).delete()
    return redirect('cart:shoppingcart')


def remove_single_item_from_cart(request, Item_id):
    item = get_object_or_404(Item, id=Item_id)
    user = request.user
    for obj in user.profile.cart_items.all():
        if obj.item.id == item.id:
            if obj.quantity>1:
                obj.quantity-=1
                obj.itemtotal=(item.price)*float(obj.quantity)
                obj.save()
            else:
                user.profile.cart_items.filter(id=obj.id).delete()
    return redirect('cart:shoppingcart')


def checkout(request):
    user = request.user
    if not user.is_authenticated:
        num_items_in_cart=0
        return render(request, 'cart/payment.html', {'num_items_in_cart': num_items_in_cart})
    all_items = user.profile.cart_items.all()
    num_items_in_cart = all_items.count()
    tot_cost=0
    for i in all_items:
        print(i.quantity)
        tot_cost += i.itemtotal
    # print(tot_cost)
    context = {'num_items_in_cart': num_items_in_cart, 'all_items':all_items, 'tot_cost':tot_cost}
    return render(request, 'cart/payment.html', context)

doctorapp/payment/views.py
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

@csrf_exempt
def payment_done(request):
    num_items_in_cart = 0
    context = {'num_items_in_cart': num_items_in_cart}
    return render(request, 'payment/done.html', context)


@csrf_exempt
def payment_cancelled(request):
    return render(request, 'payment/cancelled.html')


def payment_process(request):
    # What you want the button to do.
    user = request.user
    # user.profile.history.ordered_items = user.profile.cart_items.all()
    # user.profile.history.ordered_date = datetime.datetime.now()
    # user.save()
    # print(user.profile.history.ordered_items)
    cart_names = []
    amount = 0
    for obj in user.profile.cart_items.all():
        cart_names.append(obj.item.name)
        amount = amount + (obj.item.price * obj.quantity)

    paypal_dict = {
        "business": settings.PAYPAL_RECEIVER_EMAIL,
        "amount": amount,
        "item_name": cart_names,
        "invoice": cart_names,
        "currency_code": 'INR',
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('payment:done')),
        "cancel_return": request.build_absolute_uri(reverse('payment:cancelled')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    num_items_in_cart = user.profile.cart_items.all().count()
    context = {"form": form, 'num_items_in_cart':num_items_in_cart}
    return render(request, "payment/payment.html", context)

doctorapp/cart/templates/cart/index.html
{% include 'home/navbar.html' %}

{% load static %}
    {% if all_items %}
    <h4>{{num_items_in_cart}}</h4>

    {% for item in all_items %}
        <h5>{{ item.name }}</h5>
        <h5>{{ item.price }}</h5>
        <form action="{% url 'cart:add_to_cart' item.id %}" method="post">
            {% csrf_token %}
            <!-- <input type="number" value="1" name="quantity"> -->
            <input type="submit" value="add to cart">
        </form>
        <br>
    {% endfor %}
    {%endif%}

doctorapp/cart/templates/cart/itemlist.html
{% include 'home/navbar.html' %}
<div class="row">
    {% for item in all_items %}
    <!-- <div class="col-12 col-sm-8 col-md-2 col-lg-4"> -->
      <div class="col-md-3">
      <div class="card">
        <img class="card-img img-fluid" id="image" src="{{ item.image }}" height='2000px' width='300px' alt="Tablets">
        <div class="card-body">
          <a href="{% url 'cart:product_page' item.id %}" id="link"><h5 class="card-title">{{item.name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">Vitamin Supplement</h6></a>
          <!-- <div class="options d-flex flex-fill">
            <select class="custom-select ml-1">
                <option selected>Dosage</option>
                <option value="1">100mg</option>
                <option value="2">200mg</option>
                <option value="3">300mg</option>
            </select>
          </div> -->
          <!-- <a href="{% url 'cart:add_to_cart' item.id %}"><i class="fas fa-plus ml-2"></i></a> -->
          <div class="buy d-flex justify-content-between align-items-center">
            <div class="price text-success">
              <span><h5 class="mt-4">Rs. {{ item.price }}</h5></span>
              <a href="{% url 'cart:add_to_cart' item.id %}" class="btn btn-danger mt-3"><i class="fas fa-shopping-cart" style="color:white"></i>Add to Cart</a>
            </div>
             
          </div> 
        </div>
      </div>
    </div>
    {% endfor %}
    
    
  </div>

doctorapp/cart/templates/cart/payment.html
{% include 'home/navbar.html' %}
{% load static %}
<!-- <!DOCTYPE html> -->
<!-- <html>
<head>
  <title>Payment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  
</head> -->
<head>
  <style>
    /* Center the loader */
    #loader {
      position: absolute;
      left: 50%;
      top: 50%;
      z-index: 1;
      width: 150px;
      height: 150px;
      margin: -75px 0 0 -75px;
      border: 16px solid #f3f3f3;
      border-radius: 50%;
      border-top: 16px solid #3498db;
      width: 120px;
      height: 120px;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
    }
    
    @-webkit-keyframes spin {
      0% { -webkit-transform: rotate(0deg); }
      100% { -webkit-transform: rotate(360deg); }
    }
    
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
    
    /* Add animation to "page content" */
    .animate-bottom {
      position: relative;
      -webkit-animation-name: animatebottom;
      -webkit-animation-duration: 1s;
      animation-name: animatebottom;
      animation-duration: 1s
    }
    
    @-webkit-keyframes animatebottom {
      from { bottom:-100px; opacity:0 } 
      to { bottom:0px; opacity:1 }
    }
    
    @keyframes animatebottom { 
      from{ bottom:-100px; opacity:0 } 
      to{ bottom:0; opacity:1 }
    }
    
    #myDiv {
      display: none;
      text-align: center;
    }
    </style>
</head>
<link href="https://fonts.googleapis.com/css?family=Amiri" rel="stylesheet">
<link rel="stylesheet" href="{% static 'cart/payment1.css' %}">
<body>
  <main class="page payment-page">
    <section class="payment-form dark">
      <div class="container">
        <div class="block-heading">
          <h2>Checkout</h2>
        </div>
        <form>
          <div class="products">
            {% for oitem in all_items %}
            <div class="item">
              <span class="price">Rs. {{oitem.itemtotal}}</span>
              <p class="item-name">{{oitem.item.name}}</p>
              <p class="item-description">Qty: {{oitem.quantity}}</p>
            </div>
            {% endfor %}
            <div class="total">Total<span class="price">Rs. {{tot_cost}}</span></div>
          </div>
          <div class="card-details">
            <h3 class="title">Address</h3>
            <div class="row">
              <div class="form-group col-sm-12">
                <label for="full-name">Full Name</label>
                <input id="card-holder" type="text" class="form-control" placeholder="Full Name" aria-label="Full Name" aria-describedby="basic-addon1">
              </div>
              <div class="form-group col-sm-12">
                <label for="">Mobile Number</label>
                <input id="mobile-number" type="text" class="form-control" placeholder="Mobile Number" aria-label="Mobile Number" aria-describedby="basic-addon1">
              </div>
              <div class="form-group col-sm-12">
                <label for="address">Address</label>
                <input id="address" type="text" class="form-control" placeholder="Address" aria-label="Address" aria-describedby="basic-addon1">
              </div>
              <div class="form-group col-sm-12">
                <label for="pin">Pincode</label>
                <input id="pin" type="text" class="form-control" placeholder="Pincode" aria-label="Pincode" aria-describedby="basic-addon1">
              </div>
              <div class="form-group col-sm-12">
                <a href="{%url 'payment:process' %}" type="button" class="btn btn-primary btn-block">Proceed</a>
                <!-- <div id="loader"></div> -->
                <!-- <a href="{%url 'payment:process' %}" type="button" class="btn btn-primary ld-ext-right"
                onclick="this.classList.toggle('running')">
                  Click Me
                  <div class="ld ld-ring ld-spin"></div>
              </a> -->
                <!-- <button onclick="setTimeout(myFunction, 3000);">Proceed</button> -->
              </div>
            </div>
          </div>
        </form>
      </div>
    </section>
  </main>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script type="text/javascript">
//   function myfun(msg,duration)
// {
//  var el = '<div class="alert alert-success" role="alert">' + 
//           '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>' +
//           '<strong>Success!</strong> You have been signed in successfully!' +
//           '</div>';
// //  el.setAttribute("style","position:absolute;top:20%;left:20%;background-color:white;");
//  el.innerHTML = msg;
//   setTimeout(function() {
//     $(".alert").fadeTo(7000, 0).slideUp(7000, function(){
//         $(this).remove(); 
//     });
// }, 2000);
// //  setTimeout(function(){
// //   el.parentNode.removeChild(el);
// //  },duration);
// //  document.body.appendChild(el);
// }
var myVar;

function myFunction() {
  myVar = setTimeout(showPage, 2000);
}
function showPage() {
  document.getElementById("loader").style.display = "none";
  document.getElementById("myDiv").style.display = "block";
  // setTimeout("window.location='{%url 'payment:process' %}'",2000);
}

</script>
</body>


<!-- </html> -->

doctorapp/cart/templates/cart/product_card.html
{% include 'home/navbar.html' %}
{% load static %}


<link rel="stylesheet" href="{% static 'cart/product_card1.css' %}">

 <br>
    <div class="form-group has-search">
      <form method="POST" action="{% url 'cart:search' %}">
        {% csrf_token %}
            <input type="text" name="itemname" id="itemname"  placeholder="Search">
            <button id="but" type="submit"><i class="fa fa-search"></i></button>
        </div>
        
        
      </form>
      
    </div>

        {%comment%}<div class="row">
          {% for item in all_items %}
          <!-- <div class="col-12 col-sm-8 col-md-2 col-lg-4"> -->
            <div class="col-md-3">
              <div class="card-deck">
            <div class="card">
              <img class="card-img img-fluid" id="image" src="{{ item.image }}" height='2000px' width='300px' alt="Tablets">
              <div class="card-body">
                <a href="{% url 'cart:product_page' item.id %}" id="link"><h5 class="card-title">{{item.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Vitamin Supplement</h6></a>
                <div class="buy d-flex justify-content-between align-items-center">
                  <div class="price text-success">
                    <span><h5 class="mt-4">Rs. {{ item.price }}</h5></span>
                    <a href="{% url 'cart:add_to_cart' item.id %}" class="btn btn-danger mt-3"><i class="fas fa-shopping-cart" style="color:white"></i>Add to Cart</a>
                  </div>
                   
                </div> 
              </div>
            </div>
            </div>
          </div>
          {% endfor %} 
          </div>
          {%endcomment%}
          
          <div class="row total">
            {% for item in all_items %}
            <div class="col-md-3">
              <div class="card-deck">
                <div class="card">
                  <img src="{{item.image}}" class="card-img-top"  alt="..." height="200px" width="200px">
                  <div class="card-body">
                    <a href="{% url 'cart:product_page' item.id %}" id="link"><h5 class="card-title">{{item.name}}</h5></a>
                    <p class="card-text">Rs. {{item.price}}</p>
                    <!-- <a href="{% url 'cart:add_to_cart' item.id %}" class="btn btn-danger mt-3"><i class="fas fa-shopping-cart" style="color:white"></i>Add to Cart</a> -->
                    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                  </div>
                  <div class="card-footer">
                    <a href="{% url 'cart:add_to_cart' item.id %}" class="btn btn-danger" id="center"><i class="fas fa-shopping-cart mr-2" style="color:white"></i>Add to Cart</a>
                  </div>
                </div>
                </div>
            </div>
            {%endfor%}
          </div>
          <!-- <div class="card-deck">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div>
            
             <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div>
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div> 
          </div> -->
          
          
     
        {% if all_items.paginator.num_pages > 1 %}
        {% include 'cart/pagination.html' with items=all_items %}
    {% endif %}
  </body>

doctorapp/cart/templates/cart/shopping-cart.html
{% include 'home/navbar.html' %}
{% load static %}
<!-- <!DOCTYPE html>
<html>

<head>
	<title>Order Summary</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link href=" https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	
 </head>
-->
<!-- <link href="https://fonts.googleapis.com/css?family=Tangerine"> -->
<body> 
	<link rel="stylesheet" href="{% static 'cart/shopping_cart.css' %}">
	<main class="page">
		<section class="shopping-cart dark">
			<div class="container">
				<div class="block-heading">
					<h2>Order Summary</h2>
				</div>
				<div class="content">
					<div class="row">
						<div class="col-md-6 col-lg-8">
							<div class="items">
								{% if not all_user_items %}
								<center style="margin-top: 10%;"><h3>Your cart is empty ...</h3>
								<!-- <a href="{% url 'cart:searchpage' %}" class='btn btn-warning ml-3'>Continue Shopping</a> -->
								</center>
                                <!-- <a href="/checkout/" class='btn btn-primary float-right'>Proceed to checkout</a> -->
								{% else %}
								{% for oitem in all_user_items %}
								<div class="product">
									<div class="row">
										<div class="col-md-2">
											<img class="img-fluid mx-auto d-block image"
												src="{{oitem.item.image}}">
										</div>
										<div class="col-md-10">
											<div class="info">
												<div class="row">
													<div class="col-md-4 product-name">
														<div class="product-name">
															<a href="#">{{oitem.item.name}}</a>
															<div class="product-info">

															</div>
														</div>
													</div>
													<div class="col-md-4 quantity">
														<a href="{% url 'cart:remove_single_item_from_cart' oitem.item.id %}"><i class="fas fa-minus fa-xs mr-2"></i></a>
                                    					{{ oitem.quantity }}
														<a href="{% url 'cart:add_single_item_into_cart' oitem.item.id %}"><i class="fas fa-plus fa-xs ml-2"></i></a>
													</div>
													<div class="col-md-4 price">
														<span id="pr">Rs. {{oitem.itemtotal}}
													</span>
														<a href="{% url 'cart:remove_from_cart' oitem.item.id%}"><i class="fas fa-trash fa-xs ml-4"></i></a>
													</div>
													
												</div>
											</div>
										</div>
									</div>
								</div>
								{% endfor %}
								{% endif %}
								<center><a href="{% url 'cart:searchpage' %}" class='btn btn-warning ml-3'>Continue Shopping</a></center>
								<!-- <div class="product">
									<div class="row">
										<div class="col-md-3">
											<img class="img-fluid mx-auto d-block image"
												src="https://www.buy-pharma.md/img/uploads/42678-Absolut-3G-Box-And-Capsules.jpg">
										</div>
										<div class="col-md-8">
											<div class="info">
												<div class="row">
													<div class="col-md-5 product-name">
														<div class="product-name">
															<a href="#">Lorem Ipsum dolor</a>
															<div class="product-info">

															</div>
														</div>
													</div>
													<div class="col-md-4 quantity">
														<label for="quantity">Quantity:</label>
														<input id="quantity" type="number" value="1"
															class="form-control quantity-input">
													</div>
													<div class="col-md-3 price">
														<span>$5</span>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div> -->
							</div>
						</div>
						<div class="col-md-6 col-lg-4">
							<div class="summary">
								<h3>Summary</h3>
								<div class="summary-item"><span class="text">Subtotal</span><span
										class="price">Rs. {{ tot_cost }}</span></div>
								<div class="summary-item"><span class="text">Discount</span><span
										class="price">Rs. 0</span></div>
								<div class="summary-item"><span class="text">Shipping</span><span
										class="price">Rs. 0</span></div>
								<div class="summary-item"><span class="text">Total</span><span class="price">Rs. {{ tot_cost }}</span>
								</div>
								<a href="{% url 'cart:checkout' %}" type="button" class="btn btn-primary btn-lg btn-block">Checkout</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</main>
</body>


<!-- </html> --> 